package com.mrtdev.quoteslove.domain.quotes.models

enum class QuotesAvatar {
    HEART,
    FIRE_HEART,
    HEART_BORDER,
    HEART_PULSE,
    HEART_PULSE_BLUE,
    HEART_PUZZLE,
    MELTING_HEART,
    SKULL_HEART,
    SKULL_HEART_LOVE,
    ENVELOPE_LOVE,
    FAVORITE_FOLDER,
    HALF_HEART,
    HEART_LOCK,
    HEART_OUTLINE,
    LOVE_ARROW,
    LOVE_MESSAGE,
    LOVE_POTION,
    PHILTRE_LOVE,
    ROMANCE,
    WEDDING_CAKE,
    WEDDING_DAY,
    WEDDING_GIFT
}